name: book
on:
  workflow_dispatch:
  schedule:
    - cron: '0 15 * * SUN-WED'
jobs:
  book:
    runs-on: ubuntu-24.04
    steps:
      - uses: actions/checkout@v5
      - name: Book my ticket
        env:
          RVK_USERNAME: ${{ secrets.RVK_USERNAME }}
          RVK_PASSWORD: ${{ secrets.RVK_PASSWORD }}
        run: ./bmt.main.kts
